In [ ]:
# Christophe Nodé-Langlois

## Recommandations

Collaborative filtering : ce n'est pas de la classification

[010011010001...] vecteur de choix

On calcule la distance euclidienne (bouléen de supperposition (color px image / color px test)

In [12]:


from numpy import *

allfilms = None

def load(filename):
    f = open("./Recommandation/"+filename)
    films = set()
    n = 0
    for l in f:
        if(l[0]=='-'):
            n = n + 1
        else:
            films.add(l)
    films = list(films)
    #print(films)
    allfilms = films
    data = zeros((n,len(films)))
    i = -1
    f.seek(0)
    for l in f:
        if(l[0]=='-'):
            i=i+1
        else:
            data[i,films.index(l)] = 1
    return data, films


In [19]:
Xtrain, Films = load('db.txt') # 27 personnes et 87 films
print(len(Xtrain))
print(len(Xtrain[0]))
print(Xtrain)
print(len(Films))
print(Films)

27
87
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
87
['Leparrain2mepartie\n', 'Certainslaimentchaud\n', 'louestriendenouveau\n', 'LeseigneurdesanneauxLeretourduroi\n', 'LedocteurJivago\n', 'TaxiDriver\n', 'Laligneverte\n', 'Lavieestbelle\n', 'Titanic\n', 'Lesdentsdelamer\n', 'Gladiator\n', 'MrSmithausnat\n', '2001lodyssedelespace\n', 'Leslumiresdelaville\n', 'ButchCassidyetleKid\n', 'Lebonlabruteetletruand\n', 'Lelaurat\n', 'NewYorkMiami\n', 'Rocky\n', 'Sueursfroides\n', 'Surlesquais\n', 'Patton\n', 'Amadeus\n', 'WestSideStory\n', 'Letroisimehomme\n', 'Platoon\n', 'Voyageauboutdelenfer\n', 'LalistedeSchindler\n', 'Letrainsiffleratroisfois\n', 'Indiscrtions\n', 'LemagiciendOz\n', 'ForrestGump\n', 'BenHur\n', 'Rencontresdutroisimetype\n', 'Lafureurdevivre\n', 'Laguerredestoiles\n', 'Lamlodiedubonheur\n', 'Macadamcowboy\n', 'AnnieHall\n', 'UnAmricainParis\n', 'Lesaventuriersdela

In [20]:
def dist(x,y): # Distance (il peut être plus jdicieux de définir une autre distance)
    return sqrt(sum((x-y)**2))


In [21]:
def nn(x, X): # Le plus proche voisin
    mind = dist(x,X[0])
    imind = 0
    for i in range(1,X.shape[0]):
        d = dist(x,X[i])
        if d <= mind and i!= Moi:
            mind = d
            imind = i
    return imind


In [36]:
def suggere(Moi, Toi):
    for i in range(Xtrain[Moi].shape[0]):
        if Xtrain[Toi][i] > Xtrain[Moi][i] and Xtrain[Moi][i]==0:
            Conseils.append(i)
    print(f"Liste des {len(Conseils)} films conseillés :")
    for elm in Conseils:
        print(elm, films[elm].split())
    return Conseils


In [37]:
Moi = 13
Conseils=[]
Toi = nn(Moi,Xtrain)
#print(Xtrain[Moi])
#print(i)
#print(Xtrain[i])
print()
Conseils = suggere(Moi, Toi)
#print(Conseils)



Liste des 37 films conseillés :
0 ['Leparrain2mepartie']
3 ['LeseigneurdesanneauxLeretourduroi']
4 ['LedocteurJivago']
5 ['TaxiDriver']
9 ['Lesdentsdelamer']
10 ['Gladiator']
15 ['Lebonlabruteetletruand']
16 ['Lelaurat']
18 ['Rocky']
20 ['Surlesquais']
22 ['Amadeus']
23 ['WestSideStory']
24 ['Letroisimehomme']
25 ['Platoon']
26 ['Voyageauboutdelenfer']
27 ['LalistedeSchindler']
28 ['Letrainsiffleratroisfois']
33 ['Rencontresdutroisimetype']
34 ['Lafureurdevivre']
40 ['Lesaventuriersdelarcheperdue']
42 ['IlfautsauverlesoldatRyan']
46 ['ApocalypseNow']
49 ['Lesaffranchis']
51 ['BonnieetClyde']
53 ['PulpFiction']
56 ['Impitoyable']
58 ['Volaudessusdunniddecoucou']
59 ['LepontdelarivireKwa']
63 ['Fargo']
67 ['Lefauconmaltais']
72 ['RainMan']
73 ['Orangemcanique']
77 ['Leparrain']
78 ['Lepianiste']
79 ['Douzehommesencolre']
81 ['Casablanca']
85 ['Lexorciste']
